# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20170321_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='album',
            name='album_logo',
            field=models.URLField(),
        ),
    ]
