# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20170322_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_total',
            field=models.FloatField(default=0),
        ),
    ]
