# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20170322_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='release_year',
            field=models.IntegerField(default=0),
        ),
    ]
