# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_album_release_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
